CREATE TABLE sideutval_type (
    id SERIAL PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    predefinert BOOLEAN NOT NULL default false
);

CREATE TABLE sideutval
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id     INTEGER,
    loeysing_id INTEGER,
    sidetype    VARCHAR(255),
    side        VARCHAR(255),
    CONSTRAINT pk_sideutval PRIMARY KEY (id)
);

ALTER TABLE sideutval
    ADD CONSTRAINT FK_SIDEUTVAL_ON_LOEYSING FOREIGN KEY (loeysing_id) REFERENCES loeysing (id);

ALTER TABLE sideutval
    ADD CONSTRAINT FK_SIDEUTVAL_ON_TYPE FOREIGN KEY (type_id) REFERENCES sideutval_type (id);